name: Bug report ðŸ›
description: Report unexpected behavior in the framework
labels:
  - bug
assignees:
  - geo-madness
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the framework were you using?
      multiple: false
      options:
        - 0.6.2 (stable)
        - 0.7.0 (alpha)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the bug in detail. Attach the full traceback.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Reproducible example
      description: >
        Include a minimal, complete, reproducible example, which can be run without modification to demonstrate the problem.
      render: Python
