name: Feature request 🌀
description: Let us know about what's missing
labels:
  - feature request
assignees:
  - kikimaradoni
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the feature. What problem does it solve? 
        What would this new feature help you do that you couldn't before?
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Pseudocode
      description: >
        Make up a program making use of the proposed feature. How can it be used? 
        What would it look like in code?
      render: Python
