name: Question â“
description: Ask a question
labels:
  - question
assignees:
  - kikimaradoni
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: >
        Ask your question here. Please search through existing and closed
        issues first to ensure your question hasn't already been answered
        elsewhere.
    validations:
      required: true